// Code generated by go-swagger; DO NOT EDIT.

package access_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

//go:generate mockery -name API -inpkg

// API is the interface of the access token client
type API interface {
	/*
	   GetPageAccessToken gets page access token from facebook graph API

	   Retrieve page access token for a Facebook Page. This token can be used to access Instagram Business Account data.
	*/
	GetPageAccessToken(ctx context.Context, params *GetPageAccessTokenParams) (*GetPageAccessTokenOK, error)
}

// New creates a new access token API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for access token API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
GetPageAccessToken gets page access token from facebook graph API

Retrieve page access token for a Facebook Page. This token can be used to access Instagram Business Account data.
*/
func (a *Client) GetPageAccessToken(ctx context.Context, params *GetPageAccessTokenParams) (*GetPageAccessTokenOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetPageAccessToken",
		Method:             "GET",
		PathPattern:        "/{page_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetPageAccessTokenReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetPageAccessTokenOK), nil

}
