// Code generated by go-swagger; DO NOT EDIT.

package access_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/qcserestipy/instagram-api-go-client/pkg/sdk/v24.0/page/models"
)

// GetPageAccessTokenReader is a Reader for the GetPageAccessToken structure.
type GetPageAccessTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPageAccessTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPageAccessTokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetPageAccessTokenBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetPageAccessTokenUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetPageAccessTokenForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetPageAccessTokenNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetPageAccessTokenInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPageAccessTokenOK creates a GetPageAccessTokenOK with default headers values
func NewGetPageAccessTokenOK() *GetPageAccessTokenOK {
	return &GetPageAccessTokenOK{}
}

/*
GetPageAccessTokenOK describes a response with status code 200, with default header values.

Successfully retrieved page access token.
*/
type GetPageAccessTokenOK struct {
	Payload *models.PageAccessToken
}

// IsSuccess returns true when this get page access token o k response has a 2xx status code
func (o *GetPageAccessTokenOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get page access token o k response has a 3xx status code
func (o *GetPageAccessTokenOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get page access token o k response has a 4xx status code
func (o *GetPageAccessTokenOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get page access token o k response has a 5xx status code
func (o *GetPageAccessTokenOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get page access token o k response a status code equal to that given
func (o *GetPageAccessTokenOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetPageAccessTokenOK) Error() string {
	return fmt.Sprintf("[GET /{page_id}][%d] getPageAccessTokenOK  %+v", 200, o.Payload)
}

func (o *GetPageAccessTokenOK) String() string {
	return fmt.Sprintf("[GET /{page_id}][%d] getPageAccessTokenOK  %+v", 200, o.Payload)
}

func (o *GetPageAccessTokenOK) GetPayload() *models.PageAccessToken {
	return o.Payload
}

func (o *GetPageAccessTokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PageAccessToken)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPageAccessTokenBadRequest creates a GetPageAccessTokenBadRequest with default headers values
func NewGetPageAccessTokenBadRequest() *GetPageAccessTokenBadRequest {
	return &GetPageAccessTokenBadRequest{}
}

/*
GetPageAccessTokenBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetPageAccessTokenBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get page access token bad request response has a 2xx status code
func (o *GetPageAccessTokenBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get page access token bad request response has a 3xx status code
func (o *GetPageAccessTokenBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get page access token bad request response has a 4xx status code
func (o *GetPageAccessTokenBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get page access token bad request response has a 5xx status code
func (o *GetPageAccessTokenBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get page access token bad request response a status code equal to that given
func (o *GetPageAccessTokenBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *GetPageAccessTokenBadRequest) Error() string {
	return fmt.Sprintf("[GET /{page_id}][%d] getPageAccessTokenBadRequest  %+v", 400, o.Payload)
}

func (o *GetPageAccessTokenBadRequest) String() string {
	return fmt.Sprintf("[GET /{page_id}][%d] getPageAccessTokenBadRequest  %+v", 400, o.Payload)
}

func (o *GetPageAccessTokenBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetPageAccessTokenBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPageAccessTokenUnauthorized creates a GetPageAccessTokenUnauthorized with default headers values
func NewGetPageAccessTokenUnauthorized() *GetPageAccessTokenUnauthorized {
	return &GetPageAccessTokenUnauthorized{}
}

/*
GetPageAccessTokenUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetPageAccessTokenUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this get page access token unauthorized response has a 2xx status code
func (o *GetPageAccessTokenUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get page access token unauthorized response has a 3xx status code
func (o *GetPageAccessTokenUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get page access token unauthorized response has a 4xx status code
func (o *GetPageAccessTokenUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get page access token unauthorized response has a 5xx status code
func (o *GetPageAccessTokenUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get page access token unauthorized response a status code equal to that given
func (o *GetPageAccessTokenUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *GetPageAccessTokenUnauthorized) Error() string {
	return fmt.Sprintf("[GET /{page_id}][%d] getPageAccessTokenUnauthorized  %+v", 401, o.Payload)
}

func (o *GetPageAccessTokenUnauthorized) String() string {
	return fmt.Sprintf("[GET /{page_id}][%d] getPageAccessTokenUnauthorized  %+v", 401, o.Payload)
}

func (o *GetPageAccessTokenUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetPageAccessTokenUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPageAccessTokenForbidden creates a GetPageAccessTokenForbidden with default headers values
func NewGetPageAccessTokenForbidden() *GetPageAccessTokenForbidden {
	return &GetPageAccessTokenForbidden{}
}

/*
GetPageAccessTokenForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetPageAccessTokenForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this get page access token forbidden response has a 2xx status code
func (o *GetPageAccessTokenForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get page access token forbidden response has a 3xx status code
func (o *GetPageAccessTokenForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get page access token forbidden response has a 4xx status code
func (o *GetPageAccessTokenForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get page access token forbidden response has a 5xx status code
func (o *GetPageAccessTokenForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get page access token forbidden response a status code equal to that given
func (o *GetPageAccessTokenForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *GetPageAccessTokenForbidden) Error() string {
	return fmt.Sprintf("[GET /{page_id}][%d] getPageAccessTokenForbidden  %+v", 403, o.Payload)
}

func (o *GetPageAccessTokenForbidden) String() string {
	return fmt.Sprintf("[GET /{page_id}][%d] getPageAccessTokenForbidden  %+v", 403, o.Payload)
}

func (o *GetPageAccessTokenForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetPageAccessTokenForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPageAccessTokenNotFound creates a GetPageAccessTokenNotFound with default headers values
func NewGetPageAccessTokenNotFound() *GetPageAccessTokenNotFound {
	return &GetPageAccessTokenNotFound{}
}

/*
GetPageAccessTokenNotFound describes a response with status code 404, with default header values.

Not found
*/
type GetPageAccessTokenNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get page access token not found response has a 2xx status code
func (o *GetPageAccessTokenNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get page access token not found response has a 3xx status code
func (o *GetPageAccessTokenNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get page access token not found response has a 4xx status code
func (o *GetPageAccessTokenNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get page access token not found response has a 5xx status code
func (o *GetPageAccessTokenNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get page access token not found response a status code equal to that given
func (o *GetPageAccessTokenNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetPageAccessTokenNotFound) Error() string {
	return fmt.Sprintf("[GET /{page_id}][%d] getPageAccessTokenNotFound  %+v", 404, o.Payload)
}

func (o *GetPageAccessTokenNotFound) String() string {
	return fmt.Sprintf("[GET /{page_id}][%d] getPageAccessTokenNotFound  %+v", 404, o.Payload)
}

func (o *GetPageAccessTokenNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetPageAccessTokenNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPageAccessTokenInternalServerError creates a GetPageAccessTokenInternalServerError with default headers values
func NewGetPageAccessTokenInternalServerError() *GetPageAccessTokenInternalServerError {
	return &GetPageAccessTokenInternalServerError{}
}

/*
GetPageAccessTokenInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetPageAccessTokenInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get page access token internal server error response has a 2xx status code
func (o *GetPageAccessTokenInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get page access token internal server error response has a 3xx status code
func (o *GetPageAccessTokenInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get page access token internal server error response has a 4xx status code
func (o *GetPageAccessTokenInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get page access token internal server error response has a 5xx status code
func (o *GetPageAccessTokenInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get page access token internal server error response a status code equal to that given
func (o *GetPageAccessTokenInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetPageAccessTokenInternalServerError) Error() string {
	return fmt.Sprintf("[GET /{page_id}][%d] getPageAccessTokenInternalServerError  %+v", 500, o.Payload)
}

func (o *GetPageAccessTokenInternalServerError) String() string {
	return fmt.Sprintf("[GET /{page_id}][%d] getPageAccessTokenInternalServerError  %+v", 500, o.Payload)
}

func (o *GetPageAccessTokenInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetPageAccessTokenInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
