// Code generated by go-swagger; DO NOT EDIT.

package access_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPageAccessTokenParams creates a new GetPageAccessTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPageAccessTokenParams() *GetPageAccessTokenParams {
	return &GetPageAccessTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPageAccessTokenParamsWithTimeout creates a new GetPageAccessTokenParams object
// with the ability to set a timeout on a request.
func NewGetPageAccessTokenParamsWithTimeout(timeout time.Duration) *GetPageAccessTokenParams {
	return &GetPageAccessTokenParams{
		timeout: timeout,
	}
}

// NewGetPageAccessTokenParamsWithContext creates a new GetPageAccessTokenParams object
// with the ability to set a context for a request.
func NewGetPageAccessTokenParamsWithContext(ctx context.Context) *GetPageAccessTokenParams {
	return &GetPageAccessTokenParams{
		Context: ctx,
	}
}

// NewGetPageAccessTokenParamsWithHTTPClient creates a new GetPageAccessTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPageAccessTokenParamsWithHTTPClient(client *http.Client) *GetPageAccessTokenParams {
	return &GetPageAccessTokenParams{
		HTTPClient: client,
	}
}

/*
GetPageAccessTokenParams contains all the parameters to send to the API endpoint

	for the get page access token operation.

	Typically these are written to a http.Request.
*/
type GetPageAccessTokenParams struct {

	/* Fields.

	   Required. Comma-separated list of fields to retrieve. Use "access_token" to get the page access token.
	*/
	Fields string

	/* PageID.

	   Required. The Facebook Page ID.
	*/
	PageID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get page access token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPageAccessTokenParams) WithDefaults() *GetPageAccessTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get page access token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPageAccessTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get page access token params
func (o *GetPageAccessTokenParams) WithTimeout(timeout time.Duration) *GetPageAccessTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get page access token params
func (o *GetPageAccessTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get page access token params
func (o *GetPageAccessTokenParams) WithContext(ctx context.Context) *GetPageAccessTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get page access token params
func (o *GetPageAccessTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get page access token params
func (o *GetPageAccessTokenParams) WithHTTPClient(client *http.Client) *GetPageAccessTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get page access token params
func (o *GetPageAccessTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the get page access token params
func (o *GetPageAccessTokenParams) WithFields(fields string) *GetPageAccessTokenParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get page access token params
func (o *GetPageAccessTokenParams) SetFields(fields string) {
	o.Fields = fields
}

// WithPageID adds the pageID to the get page access token params
func (o *GetPageAccessTokenParams) WithPageID(pageID string) *GetPageAccessTokenParams {
	o.SetPageID(pageID)
	return o
}

// SetPageID adds the pageId to the get page access token params
func (o *GetPageAccessTokenParams) SetPageID(pageID string) {
	o.PageID = pageID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPageAccessTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param fields
	qrFields := o.Fields
	qFields := qrFields
	if qFields != "" {

		if err := r.SetQueryParam("fields", qFields); err != nil {
			return err
		}
	}

	// path param page_id
	if err := r.SetPathParam("page_id", o.PageID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
