// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PageAccessToken page access token
//
// swagger:model PageAccessToken
type PageAccessToken struct {

	// The page access token
	AccessToken string `json:"access_token,omitempty"`

	// The page ID
	ID string `json:"id,omitempty"`
}

// Validate validates this page access token
func (m *PageAccessToken) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this page access token based on context it is used
func (m *PageAccessToken) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PageAccessToken) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PageAccessToken) UnmarshalBinary(b []byte) error {
	var res PageAccessToken
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
