// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

//go:generate mockery --name API --keeptree --with-expecter --case underscore

// API is the interface of the media client
type API interface {
	/*
	   GetMediaByID gets fields and edges on instagram media

	   Gets fields and edges on Instagram media (album, photo, video, reel, or story).

	   Limitations:
	   - Fields that return aggregated values don't include ads-driven data.
	   - Captions don't include the @ symbol unless the app user can perform admin-equivalent tasks.
	   - Some fields, such as permalink, cannot be used on photos within albums (children).
	   - Live video Instagram Media can only be read while they are being broadcast.
	   - This API returns only data for media owned by Instagram professional accounts, not personal accounts.
	*/
	GetMediaByID(ctx context.Context, params *GetMediaByIDParams) (*GetMediaByIDOK, error)
	/*
	   UpdateMediaComments enables or disable comments on an instagram media

	   Enable or disable comments on an Instagram Media.

	   Limitations:
	   - Live video Instagram Media not supported.
	*/
	UpdateMediaComments(ctx context.Context, params *UpdateMediaCommentsParams) (*UpdateMediaCommentsOK, error)
}

// New creates a new media API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for media API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
GetMediaByID gets fields and edges on instagram media

Gets fields and edges on Instagram media (album, photo, video, reel, or story).

Limitations:
- Fields that return aggregated values don't include ads-driven data.
- Captions don't include the @ symbol unless the app user can perform admin-equivalent tasks.
- Some fields, such as permalink, cannot be used on photos within albums (children).
- Live video Instagram Media can only be read while they are being broadcast.
- This API returns only data for media owned by Instagram professional accounts, not personal accounts.
*/
func (a *Client) GetMediaByID(ctx context.Context, params *GetMediaByIDParams) (*GetMediaByIDOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetMediaByID",
		Method:             "GET",
		PathPattern:        "/{instagram_media_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetMediaByIDReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	switch value := result.(type) {
	case *GetMediaByIDOK:
		return value, nil
	case *GetMediaByIDBadRequest:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *GetMediaByIDUnauthorized:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *GetMediaByIDForbidden:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *GetMediaByIDNotFound:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *GetMediaByIDInternalServerError:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetMediaByID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
UpdateMediaComments enables or disable comments on an instagram media

Enable or disable comments on an Instagram Media.

Limitations:
- Live video Instagram Media not supported.
*/
func (a *Client) UpdateMediaComments(ctx context.Context, params *UpdateMediaCommentsParams) (*UpdateMediaCommentsOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "UpdateMediaComments",
		Method:             "POST",
		PathPattern:        "/{instagram_media_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UpdateMediaCommentsReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	switch value := result.(type) {
	case *UpdateMediaCommentsOK:
		return value, nil
	case *UpdateMediaCommentsBadRequest:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *UpdateMediaCommentsUnauthorized:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *UpdateMediaCommentsForbidden:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *UpdateMediaCommentsNotFound:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *UpdateMediaCommentsInternalServerError:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for UpdateMediaComments: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}
